Repository tl-its-umich-edu/course-inventory, pull requests merged in 2020-05, with the labels that each got.

#121 Switch to using sentinel values for two parameters in db_creator, inventory (#120)
  course_inventory/inventory.py
  db/db_creator.py
Labels: 🐛 bug

#129 Refactor drop_records, remove APPEND_TABLE_NAMES (#72)
  README.md
  config/env_blank.json
  course_inventory/inventory.py
  create_db.py
  db/db_creator.py
  mivideo/mivideo_extract.py
  run_jobs.py
Labels: config change, 🐛 bug, 📈 enhancement

#134 Refactor and validate configuration file (#29, #119, #128)
  README.md
  config/env_blank.hjson
  config/env_blank.json
  config/env_schema.hjson
  course_inventory/inventory.py
  environ.py
  online_meetings/canvas_zoom_meetings.py
  requirements.txt
Labels: Canvas, config change, 📈 enhancement, 📖 documentation

#140 Update requirements.txt (#139)
  requirements.txt
Labels: 📈 enhancement

#146 Fix duplicate dropping in AsyncEnrollGatherer (#145)
  course_inventory/async_enroll_gatherer.py
Labels: 🐛 bug

#116 add MiVideo media creation data (#92)
  README.md
  config/env_blank.hjson
  config/env_schema.hjson
  db/migrations/0015.add_mivideo_creation_tables.py
  environ.py
  mivideo/mivideo_extract.py
  mivideo/queries.py
  requirements.txt
  vocab.py
Labels: config change, 📈 enhancement, 📹 MiVideo

#153 Remove user data collection and table (#152)
  course_inventory/async_enroll_gatherer.py
  course_inventory/gql_queries.py
  course_inventory/inventory.py
  db/migrations/0016.remove_user_table.py
Labels: Canvas, database, 📈 enhancement

#151 Fetch account data from Canvas API, create and populate account table (#138)
  course_inventory/inventory.py
  db/migrations/0017.add_account_table.py
Labels: Canvas, database, 📈 enhancement

#158 Move custom formatting configuration to environ.py (#157)
  environ.py
  run_jobs.py
Labels: 🐛 bug

#143 implement `DataSourceStatus` (#142)
  README.md
  course_inventory/inventory.py
  mivideo/mivideo_extract.py
  online_meetings/canvas_zoom_meetings.py
  run_jobs.py
  vocab.py
Labels: 📈 enhancement

#167 Bump migration number for account changes to 0018 (#166)
  db/migrations/0018.add_account_table.py
Labels: database, 🐛 bug

#168 Relax data types of SIS IDs (#165)
  course_inventory/inventory.py
  db/migrations/0019.relax_sis_ids.py
Labels: Canvas, database, 🐛 bug

#163 Remove extra space in custom log format (#157)
  environ.py
  mivideo/mivideo_extract.py
Labels: 🐛 bug

#170 Support PTVSD debugging in the container
  .vscode/docker-compose-ptvsd.yaml
  .vscode/launch.json
  README.md
  requirements.txt
Labels: docker, 📖 documentation

#173 0020_add_lti_usage named incorrectly!
  db/migrations/0020.add_lti_usage.py
Labels: database

#175 Handle possibility of duplicate courses being inserted to `course` table (#174)
  course_inventory/inventory.py
Labels: Canvas, database, 🐛 bug

#179 Use DATA_DIR instead of "data" for CSV output path in inventory.py (#178)
  course_inventory/inventory.py
Labels: Canvas, 📈 enhancement

#164 I156 better published date
  course_inventory/inventory.py
  course_inventory/published_date.py
Labels: Canvas, 🐛 bug, 📈 enhancement

#181 added Apache 2 LICENSE and NOTICE files
  LICENSE
  NOTICE
Labels: 📈 enhancement, 📖 documentation

#177 Exit if max attempt limit is reached in make_request_using_api_utils (#161)
  course_inventory/inventory.py
Labels: Canvas, 🐛 bug

#182 Update .dockerignore (#180)
  .dockerignore
Labels: docker, 🐛 bug
