Repository tl-its-umich-edu/course-inventory, pull requests merged in 2020-04, with the labels that each got.

#47 Use quote_plus on db password string (#46)
  db/db_creator.py
Labels: 🐛 bug

#54 pulling right error message attribute
  canvas/published_date.py
Labels: 🐛 bug

#50 Fixes #43 - Implements paging for Zoom and Refactors request/retry
  online_meetings/canvas_zoom_meetings.py
  online_meetings/report.py
Labels: Zoom, 📈 enhancement

#38 Collect enrollment, user, and section data using the Canvas API (#23, #28)
  README.md
  canvas/async_enroll_gatherer.py
  db/migrations/0005.change_pks_to_canvas_id.py
  db/migrations/0006.modify_user.py
  db/migrations/0007.add_section_table.py
  gql_queries.py
  inventory.py
Labels: 📈 enhancement

#48 issue_32 bluejeans report
  online_meetings/bluejeans_report.py
Labels: BlueJeans

#59 Update README and env_blank.json (#26)
  README.md
  config/env_blank.json
Labels: 📖 documentation

#51 Getting canvas usage data from Canvas analytics API
  canvas/canvas_course_usage.py
  db/migrations/0008.canvas_usage_table.py
  inventory.py
Labels: 📈 enhancement

#62 Create job manager, enable append tables, add metadata tables (#14, #33)
  Dockerfile
  README.md
  config/env_blank.json
  course_inventory/__init__.py
  course_inventory/async_enroll_gatherer.py
  course_inventory/canvas_course_usage.py
  course_inventory/gql_queries.py
  course_inventory/inventory.py
  course_inventory/published_date.py
  create_db.py
  db/db_creator.py
  db/migrations/0009.add_meta_tables.py
  docker-compose.yml
  environ.py
  run_jobs.py
Labels: config change, 📈 enhancement

#70 #69 adding FK relationship for canvas_course_usage
  db/migrations/0010.add_fkc_course_usage_table.py
Labels: 📈 enhancement

#60 Fixes #53 - Refactor zoom classes to supply a term or course
  README.md
  config/env_blank.json
  online_meetings/canvas_zoom_meetings.py
Labels: 📈 enhancement

#73 Fixes #68 and fixes #44 - Fixup README based on markdown lint rules and code based on flake8
  .flake8
  .gitignore
  .markdownlint.json
  .vscode/settings.json
  README.md
  course_inventory/async_enroll_gatherer.py
  course_inventory/published_date.py
  online_meetings/.flake8
  online_meetings/bluejeans_report.py
  online_meetings/canvas_zoom_meetings.py
  online_meetings/report.py
Labels: 📖 documentation

#74 Add sis_id columns to course and course_section tables (#42)
  course_inventory/inventory.py
  db/migrations/0011.add_course_sis_ids.py
Labels: 🐛 bug, 📈 enhancement

#64 Update base URL for UM API Directory in env_blank.json
  config/env_blank.json
Labels: 🐛 bug

#87 Correct logged finished_at value and fix typo in run_jobs.py (#86)
  run_jobs.py
Labels: 🐛 bug

#79 #77 - Add support for multiple Zoom instances
  .vscode/settings.json
  README.md
  config/env_blank.json
  online_meetings/bluejeans_report.py
  online_meetings/canvas_zoom_meetings.py
  online_meetings/report.py
  online_meetings/requests_zoom_jwt.py
  requirements.txt
Labels: 📈 enhancement

#83 update Docker config to rapid development
  Dockerfile
  README.md
  docker-compose.yaml
Labels: 📈 enhancement

#93 Canvas Zoom Meetings no longer working 04/13/2020
  online_meetings/canvas_zoom_meetings.py
Labels: 🐛 bug, 📈 enhancement

#97 Pull enumerations from run_jobs.py into separate vocab.py module (#96)
  README.md
  course_inventory/inventory.py
  run_jobs.py
  vocab.py
Labels: 🐛 bug, 📈 enhancement

#81 Use loop to make waiting for MySQL container more responsive (#67)
  run_jobs.py
Labels: 📈 enhancement

#104 Identify and pull canvasdatadate using key name and value column (#103)
  course_inventory/inventory.py
Labels: 🐛 bug

#89 #88 enabling SSL to support connections within MiServer
  db/db_creator.py
Labels: 📈 enhancement

#76 integrate MiVideo usage data
  README.md
  config/env_blank.json
  db/migrations/0012.add_mivideo_usage_table.py
  environ.py
  mivideo/.flake8
  mivideo/__init__.py
  mivideo/mivideo_extract.py
  mivideo/queries.py
  requirements.txt
  run_jobs.py
  vocab.py
Labels: 📈 enhancement, 📹 MiVideo

#106 Move sleep until after MySQL container check (#105)
  run_jobs.py
Labels: 📈 enhancement

#108 Update Codacy badge to use legacy organization (for now) (#107)
  README.md
Labels: 🐛 bug

#112 fix MiVideo `data_updated_at` timestamp (#111)
  mivideo/mivideo_extract.py
Labels: 🐛 bug, 📹 MiVideo

#110 Improve DBCreator (#66, #84, #109)
  config/env_blank.json
  course_inventory/inventory.py
  create_db.py
  db/db_creator.py
  mivideo/mivideo_extract.py
  run_jobs.py
Labels: 🐛 bug, 📈 enhancement

#115 Add term table, accomodate multiple terms, fix course.sis_id bug (#113, #117)
  README.md
  config/env_blank.json
  course_inventory/inventory.py
  db/migrations/0013.add_term_table.py
  db/migrations/0014.change_course_sis_id_data_type.py
  online_meetings/canvas_zoom_meetings.py
Labels: config change, 🐛 bug, 📈 enhancement
