Repository tl-its-umich-edu/course-inventory, pull requests merged in 2020-03, with the labels that each got.

#12 Use ApiUtil.get_next_page for paging (#11)
  inventory.py
Labels: bug, enhancement

#10 Create db module, change to inserting data into MySQL database (#4)
  .gitignore
  Dockerfile
  config/env_blank.json
  create_db.py
  db/__init__.py
  db/db_creator.py
  db/tables.py
  inventory.py
  requirements.txt
Labels: enhancement

#17 Manage database with yoyo-migrations (#13)
  create_db.py
  db/db_creator.py
  db/migrations/0001.init_inventory_db.py
  db/tables.py
  inventory.py
  requirements.txt
Labels: enhancement

#16 Allow for ENV_PATH variable for OpenShift integration, add documentation (#1, #3)
  README.md
  config/secrets/.gitignore
  create_db.py
  inventory.py
Labels: documentation, enhancement

#18 I8 get course published date
  .gitignore
  README.md
  canvas/__init__.py
  canvas/published_date.py
  config/env_blank.json
  db/migrations/0002.add_col_published_date.py
  db/migrations/0003.created_date_datatype_change.py
  inventory.py
  requirements.txt
Labels: enhancement

#24 Add sis_id to user table (#22)
  db/migrations/0004.add_sis_id.py
  inventory.py
Labels: enhancement
